### ISSUE TITLE
[1.0.0.250] [1.6.4] missing required element 'version'

### ISSUE THREAD

**Issue by bhi-elliot** [Chicken-Bones/ForgeMultipart#141]
Just a warning that doesn't do much harm, but thought I'd mention it.
Getting this at server start:

[WARNING] Mod ForgeMicroblock is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0.0.233
[WARNING] Mod ForgeMultipart is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0.0.233
[WARNING] Mod McMultipart is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0.0.233

**Comment by Lockhart712** [comment]
Does it pose a problem? When I load a modpack it says this for multiple mods, and I just want to make sure it isn't a big deal

(Here's one):
[10:43:58] [Client thread/WARN] [betterbuilderswands]: Mod betterbuilderswands is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 0.6.1
