### ISSUE TITLE
Creating multipart blocks with /setblock syntax (1.7.10)

### ISSUE THREAD

**Issue by Sukasa** [Chicken-Bones/ForgeMultipart#298]
I apologize, as this likely isn't the best area to ask this.

I am trying to use the /setblock replace syntax in order to create/change microblocks.  However although I get output that the block was placed, nothing is actually there.  Checking the chunk's saved data seems to show that the block is placed (0xC2 byte in the block data array instead of 0x00), however no TileEntity is listed in the chunk.

In order to create the block, I took the NBT data as saved in a normally-placed button from Project Red, and replicated the NBT tag from the saved chunk into the command

/setblock 2 5 1 ForgeMultipart:block 0 replace {parts: [{colorMeta: 2, inv: 0, meta: 2, id: "pr_flightbutton"}], id: "savedMultipart"}

Is there any particular reason that this command would apparently produce an "empty" multipart block instead of, well, a block with a button in it?  Although not listed here, I've tried to create other multipart blocks with a mix of ProjectRed and non-ProjectRed blocks and had the same result - it always creates a "ghost" tile.  I can place any other tile into it just fine and it'll act normal, but rain reacts as though there is indeed a block present.

**Comment by Entoarox** [comment]
multiparts are tile entities that render their contents during chunk-load, the /setblock command doesnt properly initialise the multipart tile entity, idk if it should be considered a bug in fmp or in the /setblock command (thus a forge issue) though.

**Comment by Chicken-Bones** [comment]
Yeah, that's definitely not going to work due to the way FMP is implemented, and as there are no hooks for this command, this cannot be fixed without ASM.
