### ISSUE TITLE
saw item icon suggestion!

### ISSUE THREAD

**Issue by wiiv** [Chicken-Bones/ForgeMultipart#299]
Can you add a config option to have an item icon instead of the model for the saw?

**Comment by Chicken-Bones** [comment]
Why, and are you willing to provide sprites?

**Comment by wiiv** [comment]
I am willing to provide sprites! Just because I find the model too detailed for minecraft, and I might not be the only one to think so. So I tough it could be a nice addition. Thank you for answering!

**Comment by Chicken-Bones** [comment]
ok, post some sprites, I'll add the option

**Comment by wiiv** [comment]
stone saw:
http://imgur.com/kBLQ0HR

iron saw:
http://imgur.com/lyKGc4Z

diamond saw:
http://imgur.com/gLVTiIb

I hope you like them! Thank you once again!

**Comment by MalkContent** [comment]
this I like :)

**Comment by CubeWrench202** [comment]
Redpower-ish, i like it :3

**Comment by Chicken-Bones** [comment]
Added by a93d9cbbd9ed4e4c1622c3a109addedccee1538e (1.7.10-1.1.1.321)
