### ISSUE TITLE
Block not registering

### ISSUE THREAD

**Issue by Azikai** [Chicken-Bones/ForgeMultipart#300]
HEE Glowing Obsidian won't register and make microblocks.

In the configs I have it as: "HardcoreEnderExpansion.obsidian_special_glow":0-2

Tried FMPI, but a load of errors from missing blocks from other people. In FMPI, glowing obsidian microblocks worked, but idk.

Any clue?

**Comment by Azikai** [comment]
Also, I have tried several variations of that, but nothing works >.>

**Comment by Chicken-Bones** [comment]
use NEI's item dump to find the block name?

**Comment by Azikai** [comment]
Thats what I used. Didn't work >,>

**Comment by Azikai** [comment]
Ah! Got it to work! It seems I had to make the blocks under its ID seperately.... Thanks >.>
