### ISSUE TITLE
Request: 3/4 1/2 1/4  Pillar

### ISSUE THREAD

**Issue by Crazy-KSK** [Chicken-Bones/ForgeMultipart#303]
http://i.imgur.com/JNsxOc0.jpg
http://i.imgur.com/i0ZzZ7H.jpg
filling the middle here would be the use case I am thinking of myself but I'm sure there is a lot more creative ways to use them

**Comment by Chicken-Bones** [comment]
I can't do that, because microblocks have 1/8th block resolution and not
1/16th, so all their edges must be on a 1/4 1/2 3/4

**Comment by Crazy-KSK** [comment]
let me reiterate, what I'm thinking  is  the missing part in a hollow cover that can be stacked on top of each other just like covers can

**Comment by Chicken-Bones** [comment]
I see what you mean now. I don't think there's enough demand to justify the time investment for something like this, though of course, anyone is welcome to write a plugin.
