### ISSUE TITLE
Torches cannot be placed on posts/pillars in vertical position

### ISSUE THREAD

**Issue by mcgraj3** [Chicken-Bones/ForgeMultipart#317]
Not sure if this is a bug or simply the mechanics of Multipart at work. I was trying to build some custom torch stands using copper posts. The torches won't attach on top even though the posts are 1 block high (vertical position, centered). Same results with pillars.

(using ForgeMultipart-1.7.10-1.1.1.320-universal)

**Comment by Chicken-Bones** [comment]
aah, I'll add something for that

**Comment by Chicken-Bones** [comment]
I did it 8f1787441267418301085205fb6e70270aa07d80 (1.7.10-1.1.1.326)
