### ISSUE TITLE
#ForgeMultiPart Duplicate error# with ForgeMicroblocks and McMultipart

### ISSUE THREAD

**Issue by CreepersGamingz** [Chicken-Bones/ForgeMultipart#318]
As soon as i installed ForgeMultipart it allways come's up with a message saying;

============================================================
Forge Mod Loader has found a problem with your minecraft installation
You have mod sources that are duplicate within your system
          Mod Id : File name
ForgeMicroblock : ForgMultipart-1.7.10-1.1.1.326-universal.jar
ForgeMicroblock : ForgMultipart-1.7.10-1.1.0.314-universal.jar
ForgeMultipart : ForgMultipart-1.7.10-1.1.1.326-universal.jar
ForgeMultipart : ForgMultipart-1.7.10-1.1.0.314-universal.jar
McMultipart : ForgMultipart-1.7.10-1.1.1.326-universal.jar
McMultipart : ForgMultipart-1.7.10-1.1.0.314-universal.jar
===============================================

And ive tried getting rid of ForgeMultipart but it deletes itself from my mods folder.
And it doesnt give me a crash report so i can see if there are any other errors maybe.

Heres a picture as well.
![6507dfd2a9c55bac4d2aae503460f81d](https://cloud.githubusercontent.com/assets/11609103/6883802/f30c6eea-d612-11e4-804b-483153d3099b.png)

**Comment by luacs1998** [comment]
Some mods that use the FMP library seem to like to auto-download FMP. Look in your mods folder and remove any duplicates.

**Comment by Chicken-Bones** [comment]
/mods/1.7.10
delete the old one

**Comment by CreepersGamingz** [comment]
Thanks So much :D

**Comment by FrikenCanadiansEH** [comment]
Sorry for reviving this but I am having this same issue as OP, I've tried deleting them but they just recreate themselves :| , Log: https://www.gravitezero.com/src/3U211W.txt
