### ISSUE TITLE
Build #329 Microblocks can only be placed in one orientation

### ISSUE THREAD

**Issue by juniorjunior** [Chicken-Bones/ForgeMultipart#319]
All microblocks that take up a whole "face" of a block seem to only be able to be placed horizontally at the bottom of the block space, regardless of type of size of microblock. Other types of microblocks which do not take up a whole face (i.e. strips, corners, etc.) seem to behave as expected. Builds #327 and earlier seem to function as expected.

**Comment by Chicken-Bones** [comment]
Fixed by 7b4e763641a0d5124d9cfdf3eb9f2428eb6d5a3d (1.7.10-1.1.2.330)
