### ISSUE TITLE
ASMMixinCompiler encountering errors on dedicated server. [Builds 336,338,340,341]

### ISSUE THREAD

**Issue by ProgrammerHero** [Chicken-Bones/ForgeMultipart#329]
I started up a dedicated server running Forge 1400 and ForgeMultipart 340 (also happens with 341) and was greeted with [A mixin trait related crash](http://pastebin.com/gJFyuJpi).  This only happened on the server, the client running 340 ran just fine.

I attempted to track it down by rolling back ForgeMultipart to 338, 336, and 334.  Build 334 worked fine, but 336 and 338 both gave me [this error](http://pastebin.com/YG6WDLkR) which did not occur in 340 or 341 (not sure if it is fixed or just hidden by the other error).

**Comment by Chicken-Bones** [comment]
Fixed as of dd928e75758d172237789e02356c17044de4e39a #342
