### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by MrKyurem** [Chicken-Bones/ForgeMultipart#330]
The only two errors are for Forge Multipart and ForgeMicroblock. Where am I being stupid?

http://pastebin.com/EjRgG2L8

**Comment by Chicken-Bones** [comment]
Weather pony is also there. Try FMP 1.1.2.334

**Comment by MrKyurem** [comment]
I'm not sure whether this is the same problem or a new one, but the "77 more" has turned into a "78 more." 

http://pastebin.com/iP7m0Vrh

**Comment by Chicken-Bones** [comment]
Looks like there's an incompatiblity with WeatherPony, try reporting to
that author

**Comment by MrKyurem** [comment]
Removing the WeatherPony stuff fixed the problem. Thanks for responding so quickly! I'll be sure to let them know about the incompatibility.
