### ISSUE TITLE
NPE with Exception Message in MultipartCPH.handlePacket

### ISSUE THREAD

**Issue by SquidDev** [Chicken-Bones/ForgeMultipart#348]
Some exceptions (such as NPEs) do not contain an error message, and so [this statement](https://github.com/Chicken-Bones/ForgeMultipart/blob/master/src/codechicken/multipart/handler/packethandlers.scala#L48) (`case e:RuntimeException if e.getMessage.startsWith("DC: ")`) fails, making it harder to trace exceptions.

A simple:
```scala
case e:RuntimeException if e.getMessage != null && e.getMessage.startsWith("DC: ")
```
would fix it.

**Comment by Chicken-Bones** [comment]
Done

**Comment by SquidDev** [comment]
Thanks!
