### ISSUE TITLE
Problem with ExtraUtils+ForgeMultipart

### ISSUE THREAD

**Issue by iGoodie** [Chicken-Bones/ForgeMultipart#350]
I use ForgeMultipart saw to cut "Thickened Glass" into two.
Then i put one of them down. And then i put another one to the block right next to it. Insta-crash
Here's the crash log: http://pastebin.com/wFVkCWa2

**Comment by TheJulianJES** [comment]
ExU error I think.

**Comment by Chicken-Bones** [comment]
Yep
