### ISSUE TITLE
Replaced Blocks crash

### ISSUE THREAD

**Issue by Speiger** [Chicken-Bones/ForgeMultipart#369]
When you replace blocks FMP crashes instantly.
It is not good to replace blocks i know that too, but it was the best solution and out of +130 mods is your mod the only one who crashes that. (Note: CoFH lib provide that feature to replace blocks).
Please fix that so that replaced blocks do not crash the game.
And note: its not the fault of the modder who replaces blocks, if you would do stuff how every mod there should be no crash at all

Crashreport: http://pastebin.com/3NAKvDAP

**Comment by Chicken-Bones** [comment]
If only it were that simple

**Comment by Chicken-Bones** [comment]
Might actually be a cofh issue

**Comment by Speiger** [comment]
No it is not chickenbones...
You are making something weird while loading the data...
Why are you using a Unlocalized name for loading your parts?

**Comment by Speiger** [comment]
Maybe it helps which block i am replacing.
Its the glowstone block. and it even extends the Glowstone block so if you need something from it your thing should not even nodest it.

**Comment by Speiger** [comment]
but could you fix that so i do not need to worry about that part anymore?
I would provide you with a dev version of that mod so you can test if you need that. (Note: unreleased mod)

**Comment by Speiger** [comment]
@Chicken-Bones do you take care about that?

**Comment by Chicken-Bones** [comment]
I use unlocalised name because it's a universal system for interfacing with all block content, obviously the replaced block is not being updated in the block name map

**Comment by Speiger** [comment]
yeah ok... i am trying something... I replace the block after the mods got loaded (postinit) so that should not interfear with your icons at all... Because i am using the same textures it also should have no effect at all^^"
Just so you know you can read the CothLib override function but this one i am not using because it requires a ASM envioment which i do not want to have. Reflection is ok enough.

**Comment by Speiger** [comment]
Ok. Reason beeing that it crashes is partly my fault and partly yours. I forgot to register a replacement name to the real one. Yours is to doublecheck the classes... Anyway i close this now because i could reproduce the crash and could fix that. And that also should work with FMP too^^"

**Comment by Speiger** [comment]
Ok fixed...

**Comment by Chicken-Bones** [comment]
Great

**Comment by Speiger** [comment]
@Chicken-Bones also it replaces automaticly all Glowstone covers with my ones. So there is no problem with adding that mod or removing it ^^
